# Generated by Django 5.0.7 on 2024-08-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_faculty_customuser_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOralDefenseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('room', models.CharField(max_length=100)),
                ('panels', models.CharField(max_length=255)),
                ('proponents', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
