# Generated by Django 5.0.7 on 2024-08-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_preoraldefenseschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreOralDefenseSchedule',
        ),
    ]
