# Generated by Django 5.0.7 on 2024-08-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='other_expertise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
