# Generated by Django 5.0.7 on 2024-08-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reco_app', '0002_faculty_other_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='other_expertise',
        ),
        migrations.AddField(
            model_name='faculty',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='years_of_teaching',
            field=models.IntegerField(),
        ),
    ]
