# Generated by Django 5.0.7 on 2024-08-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reco_app', '0004_faculty_other_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='other_expertise',
        ),
        migrations.AddField(
            model_name='faculty',
            name='other_expertise_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='other_expertise_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='has_master_degree',
            field=models.BooleanField(),
        ),
    ]
