# Generated by Django 5.0.7 on 2024-08-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reco_app', '0005_remove_faculty_other_expertise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='other_expertise_text',
            new_name='other_expertise',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='other_expertise_checkbox',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='has_master_degree',
            field=models.BooleanField(default=False),
        ),
    ]
