# Generated by Django 5.0.7 on 2024-08-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reco_app', '0006_rename_other_expertise_text_faculty_other_expertise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='other_expertise',
        ),
    ]
