# Generated by Django 5.0.7 on 2024-08-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lunch_break',
            field=models.BooleanField(default=False),
        ),
    ]
