# Generated by Django 5.0.7 on 2024-08-03 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_scheduler_app', '0002_schedule_lunch_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepod',
            name='lunch_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulepod',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_scheduler_app.groupinfoth'),
        ),
        migrations.AlterField(
            model_name='schedulepod',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_scheduler_app.groupinfopod'),
        ),
    ]
