# Generated by Django 5.0.7 on 2024-07-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('years_of_teaching', models.PositiveIntegerField()),
                ('mobile_web_dev', models.BooleanField(default=False)),
                ('database_management', models.BooleanField(default=False)),
                ('ai_ml', models.BooleanField(default=False)),
                ('iot', models.BooleanField(default=False)),
                ('cybersecurity', models.BooleanField(default=False)),
                ('gis', models.BooleanField(default=False)),
                ('data_analytics', models.BooleanField(default=False)),
                ('ecommerce_digital_marketing', models.BooleanField(default=False)),
                ('educational_technology', models.BooleanField(default=False)),
                ('healthcare_informatics', models.BooleanField(default=False)),
                ('game_development', models.BooleanField(default=False)),
                ('hci', models.BooleanField(default=False)),
                ('agricultural_technology', models.BooleanField(default=False)),
                ('smart_city_technologies', models.BooleanField(default=False)),
                ('fintech', models.BooleanField(default=False)),
                ('computer_networks', models.BooleanField(default=False)),
                ('software_engineering', models.BooleanField(default=False)),
                ('multimedia_graphics', models.BooleanField(default=False)),
            ],
        ),
    ]
