# Generated by Django 5.0.7 on 2024-07-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='has_master_degree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
