# Generated by Django 5.0.7 on 2024-07-26 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0003_faculty_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_title', models.CharField(max_length=255)),
                ('number_of_advisees', models.PositiveIntegerField(default=1)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco_app.faculty')),
            ],
        ),
    ]
