# Generated by Django 5.0.7 on 2024-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0005_remove_adviser_number_of_advisees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
