# Generated by Django 5.0.7 on 2024-07-27 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reco_app', '0006_faculty_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfoTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.PositiveIntegerField()),
                ('section', models.CharField(max_length=50)),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco_app.faculty')),
            ],
        ),
    ]
