# Generated by Django 5.0.7 on 2024-07-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0004_alter_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
