# Generated by Django 5.0.7 on 2024-07-28 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0006_faculty_is_active'),
        ('scheduler_app', '0005_schedule_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfoPOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(blank=True, max_length=100, null=True)),
                ('member2', models.CharField(blank=True, max_length=100, null=True)),
                ('member3', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(max_length=50)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advised_groups', to='reco_app.faculty')),
                ('capstone_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_groups', to='reco_app.faculty')),
            ],
        ),
    ]
