# Generated by Django 5.0.7 on 2024-07-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0006_faculty_is_active'),
        ('scheduler_app', '0006_groupinfopod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfopod',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_adviser', to='reco_app.faculty'),
        ),
        migrations.AlterField(
            model_name='groupinfopod',
            name='capstone_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_teacher', to='reco_app.faculty'),
        ),
        migrations.CreateModel(
            name='SchedulePOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviserPOD_sched', to='reco_app.faculty')),
                ('capstone_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_teacherPOD_sched', to='reco_app.faculty')),
                ('faculty1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty1POD', to='reco_app.faculty')),
                ('faculty2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty2POD', to='reco_app.faculty')),
                ('faculty3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty3POD', to='reco_app.faculty')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_POD', to='scheduler_app.groupinfopod')),
            ],
        ),
    ]
