# Generated by Django 5.0.7 on 2024-08-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0007_alter_groupinfopod_adviser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='has_been_rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
