# Generated by Django 5.0.7 on 2024-08-06 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0008_schedule_has_been_rescheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='has_been_rescheduled',
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
